<div class="container">
<div class="auth-form" id="login">
<div class="auth-form-header">
        <h1><?php echo $this->translate("Sign in"); ?></h1>
</div>
        <?php 
$form->setAttribute('action', $this->url('admin/login'));
$form->prepare();
?>
<?php 
echo $this->form()->openTag($form);
?>
<div class="auth-form-body">
<?php 
$identity = $form->get('identity');
echo $this->formLabel($identity);
echo $this->formInput($identity);
//echo $this->formElementErrors($identity);

$credential = $form->get('credential');
echo $this->formLabel($credential);
?>
 <a href="<?php echo $this->url('admin/password_reset') ?>"><?php echo $this->translate('(forgot password)'); ?></a>
<?php 
echo $this->formInput($credential);
//echo $this->formElementErrors($credential);

echo $this->formElement($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
</div>
<?php 
echo $this->form()->closeTag();
?>
</div>
</div> <!-- /container -->